// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/activegraph/FailuresPage.tsx": () => import("../components/mockups/activegraph/FailuresPage.tsx"),
  "./components/mockups/activegraph/InfoModal.tsx": () => import("../components/mockups/activegraph/InfoModal.tsx"),
  "./components/mockups/activegraph/PatchesPage.tsx": () => import("../components/mockups/activegraph/PatchesPage.tsx"),
  "./components/mockups/activegraph/RelationsPage.tsx": () => import("../components/mockups/activegraph/RelationsPage.tsx"),
  "./components/mockups/activegraph/ToolsPage.tsx": () => import("../components/mockups/activegraph/ToolsPage.tsx"),
  "./components/mockups/activegraph/TraceFiltered.tsx": () => import("../components/mockups/activegraph/TraceFiltered.tsx")
};
